version: '3.8'

services:
  web:
    build: .
    container_name: attendance_automation
    ports:
      - "920:920"
    secrets:
      - app_secret
      - g_creds
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

secrets:
  app_secret:
    file: .env
  g_creds:
    file: credentials.json
